[Tests] Support Python 3.7
Updates test assertions that rely on implicit enum conversion to int, so
that they work in Python 3.7, avoiding:

  TypeError: list indices must be integers or slices, not openassetio._openassetio.log.Severity

On windows, in Python 3.7, WindowsPath objects don't convert to a
string, and so the subprocess fails.

Part of #660.

Signed-off-by: Tom Cowland <tom@foundry.com>